<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputPath Condition="'$(Configuration)'=='Release'">..\..\ComponentsLibraries</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ControlsLibraryNet90" Version="1.0.0" />
    <PackageReference Include="DepartmentAccountingContracts" Version="1.0.0" />
  </ItemGroup>

</Project>
